# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinc', '0002_auto_20170712_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
