# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thinc', '0003_idea_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='author',
            new_name='user',
        ),
    ]
